<?php
define("CONSUMER_SECRET","YOUR_CONSUMER_SECRET");
define("ACCESS_TOKEN","YOUR_ACCESS_TOKEN");
define("ACCESS_TOKEN_SECRET","YOUR_ACCESS_TOKEN_SECRET");
define("CONSUMER_KEY","YOUR_CONSUMER_KEY");
define("CALLBACK_URL", "http://callback.url");
?>
